window.RADICAL_HINTS = {
  "亻": "person radical",
  "女": "woman / female",
  "子": "child",
  "口": "mouth",
  "宀": "roof",
  "讠": "speech / language",
  "氵": "water",
  "扌": "hand",
  "艹": "grass / plant",
  "木": "wood / tree",
  "日": "sun / day",
  "月": "moon / body / flesh",
  "忄": "heart / feeling",
  "心": "heart",
  "辶": "movement / walking",
  "门": "door",
  "贝": "shell / money",
  "钅": "metal",
  "饣": "food",
  "纟": "silk / thread",
  "火": "fire",
  "雨": "rain",
  "田": "field",
  "土": "earth",
  "禾": "grain",
  "页": "head / page",
  "耳": "ear",
  "目": "eye",
  "石": "stone",
  "言": "speech",
  "车": "vehicle",
  "衣": "clothing radical",
  "足": "foot",
  "虫": "insect"
};

window.CHAR_DETAILS = {
  "你": { pinyin: "nǐ", radical: "亻", components: ["尔"], clue: "The person radical 亻 often appears in people words. Together this character means “you”." },
  "好": { pinyin: "hǎo", radical: "女", components: ["子"], clue: "A classic beginner character: 女 “woman” + 子 “child”, forming the idea “good / well”." },
  "我": { pinyin: "wǒ", components: ["手", "戈"], clue: "Learn 我 as the first-person pronoun “I / me”. The components help you remember the shape." },
  "他": { pinyin: "tā", radical: "亻", components: ["也"], clue: "The person radical marks this as a person-related pronoun: “he / him”." },
  "她": { pinyin: "tā", radical: "女", components: ["也"], clue: "The female radical 女 marks this pronoun as “she / her”." },
  "们": { pinyin: "men", radical: "亻", components: ["门"], clue: "Added after pronouns, 们 makes them plural, as in 我们 and 你们." },
  "名": { pinyin: "míng", components: ["夕", "口"], clue: "A common mnemonic links evening 夕 and mouth 口 to the idea of calling a name." },
  "字": { pinyin: "zì", radical: "宀", components: ["子"], clue: "Under a roof 宀 with a child 子: a helpful clue for 字 “character / written word”." },
  "学": { pinyin: "xué", radical: "子", components: ["⺍", "冖", "子"], clue: "A learner under a roof is a useful memory clue for 学 “study / learn”." },
  "校": { pinyin: "xiào", radical: "木", components: ["交"], clue: "The 木 radical is common in many characters. In 学校, 校 helps form the word “school”." },
  "老": { pinyin: "lǎo", components: ["耂", "匕"], clue: "Often linked to age or familiarity; in 老师 it helps form “teacher”." },
  "师": { pinyin: "shī", radical: "巾", components: ["丨", "一"], clue: "Used in titles for skilled people; 师 contributes “teacher / master”." },
  "朋": { pinyin: "péng", components: ["月", "月"], clue: "朋 appears in 朋友 and helps build the idea of a friend." },
  "友": { pinyin: "yǒu", components: ["又", "𠂇"], clue: "友 is the second character in 朋友, the everyday word for “friend”." },
  "衣": { pinyin: "yī", radical: "衣", components: [], clue: "衣 is the original “clothing” character and often appears in words about clothes." },
  "服": { pinyin: "fú", radical: "月", components: ["卩", "又"], clue: "In 衣服, 服 helps form the everyday word for clothes and is also used in words about wearing or serving." },
  "水": { pinyin: "shuǐ", components: [], clue: "A basic single-character word meaning “water”." },
  "茶": { pinyin: "chá", radical: "艹", components: ["人", "木"], clue: "The grass radical 艹 often appears in plant-related words, which fits tea 茶." },
  "米": { pinyin: "mǐ", components: [], clue: "A basic character meaning “rice”." },
  "饭": { pinyin: "fàn", radical: "饣", components: ["反"], clue: "The food radical 饣 marks 饭 as a food-related word: meal / cooked rice." },
  "苹": { pinyin: "píng", radical: "艹", components: ["平"], clue: "The grass radical 艹 is common in plant words; 苹 appears in 苹果 “apple”." },
  "果": { pinyin: "guǒ", radical: "木", components: ["田", "木"], clue: "果 means fruit and often appears in food vocabulary." },
  "电": { pinyin: "diàn", components: ["日", "乚"], clue: "电 contributes the idea of electricity in words like 电话 and 电脑." },
  "话": { pinyin: "huà", radical: "讠", components: ["舌"], clue: "The speech radical 讠 marks this as a speaking-related character: words / speech." },
  "脑": { pinyin: "nǎo", radical: "月", components: ["㐫"], clue: "脑 means brain; in 电脑 it helps form the word “computer”." },
  "视": { pinyin: "shì", radical: "见", components: ["礻"], clue: "视 is tied to seeing / vision, which fits 电视 “television”." },
  "汉": { pinyin: "hàn", radical: "氵", components: ["又"], clue: "The water radical 氵 appears in 汉; in 汉语 it refers to “Chinese / Han”." },
  "语": { pinyin: "yǔ", radical: "讠", components: ["吾"], clue: "The speech radical 讠 marks this as a language-related character: “language / speech”." },
  "中": { pinyin: "zhōng", components: [], clue: "中 means middle / center and appears in 中国 “China”." },
  "国": { pinyin: "guó", radical: "囗", components: ["玉"], clue: "The outer enclosure 囗 often suggests a bounded area; 国 means country." },
  "北": { pinyin: "běi", components: [], clue: "北 is the character for “north”." },
  "京": { pinyin: "jīng", components: ["亠", "口", "小"], clue: "京 often relates to a capital city, as in 北京.“" },
  "医": { pinyin: "yī", radical: "匚", components: ["矢"], clue: "医 relates to medicine and appears in 医生 “doctor”." },
  "生": { pinyin: "shēng", components: [], clue: "生 can mean life, birth or student, depending on the word. In 学生 it means “student”." },
  "人": { pinyin: "rén", components: [], clue: "A basic single-character word meaning “person”." },
  "家": { pinyin: "jiā", radical: "宀", components: ["豕"], clue: "Under a roof 宀: 家 means home / family." },
  "看": { pinyin: "kàn", components: ["手", "目"], clue: "Hand 手 over eye 目 is a useful memory clue for 看 “to look / watch”." },
  "听": { pinyin: "tīng", radical: "口", components: ["斤"], clue: "The mouth radical 口 appears in many speaking and listening words; 听 means “listen”." },
  "说": { pinyin: "shuō", radical: "讠", components: ["兑"], clue: "The speech radical 讠 clearly marks 说 as “to speak / say”." },
  "读": { pinyin: "dú", radical: "讠", components: ["卖"], clue: "The speech radical 讠 also appears in 读 “to read”." },
  "写": { pinyin: "xiě", radical: "冖", components: ["与"], clue: "写 means “to write”. Focus on the full shape if the components feel less transparent." },
  "吃": { pinyin: "chī", radical: "口", components: ["乞"], clue: "The mouth radical 口 is a good clue: 吃 means “eat”." },
  "喝": { pinyin: "hē", radical: "口", components: ["曷"], clue: "Again the mouth radical 口: 喝 means “drink”." },
  "睡": { pinyin: "shuì", radical: "目", components: ["垂"], clue: "The eye radical 目 makes sense in 睡 “to sleep”." },
  "觉": { pinyin: "jiào / jué", radical: "见", components: ["⺍", "冖"], clue: "In 睡觉 it is pronounced jiào and helps form the word “sleep”." },
  "做": { pinyin: "zuò", radical: "亻", components: ["故"], clue: "The person radical 亻 appears in 做, the common verb “do / make”." },
  "买": { pinyin: "mǎi", components: [], clue: "A high-frequency verb meaning “buy”." },
  "开": { pinyin: "kāi", components: [], clue: "A versatile character meaning open / start / drive depending on the context." },
  "坐": { pinyin: "zuò", radical: "土", components: ["人", "人", "土"], clue: "Two people over earth is a helpful shape clue for 坐 “sit”." },
  "住": { pinyin: "zhù", radical: "亻", components: ["主"], clue: "The person radical 亻 makes sense in 住 “live / reside”." },
  "工": { pinyin: "gōng", components: [], clue: "工 means work / labor." },
  "作": { pinyin: "zuò", radical: "亻", components: ["乍"], clue: "Together with 工 it forms 工作 “work / job”." },
  "爱": { pinyin: "ài", components: ["爫", "冖", "心", "夂"], clue: "爱 contains the heart component 心, which is a nice clue for “love”." },
  "喜": { pinyin: "xǐ", components: ["士", "口", "口"], clue: "喜 contributes the “like / joy” idea in 喜欢." },
  "欢": { pinyin: "huān", radical: "欠", components: ["又"], clue: "欢 contributes joy / delight in 喜欢 “to like”." },
  "想": { pinyin: "xiǎng", radical: "心", components: ["相", "心"], clue: "The heart component 心 is a useful clue in 想 “think / want”." },
  "会": { pinyin: "huì", components: ["人", "云"], clue: "会 can mean “can / know how to” or “meeting” in other contexts." },
  "能": { pinyin: "néng", radical: "月", components: ["匕", "匕", "厶"], clue: "能 expresses ability: can / be able to." },
  "好": { pinyin: "hǎo", radical: "女", components: ["子"], clue: "女 “woman” + 子 “child”: a common memory clue for 好 “good / well”." },
  "大": { pinyin: "dà", components: [], clue: "A basic adjective meaning “big”." },
  "小": { pinyin: "xiǎo", components: [], clue: "A basic adjective meaning “small”." },
  "多": { pinyin: "duō", components: ["夕", "夕"], clue: "A basic adjective meaning “many / much”." },
  "少": { pinyin: "shǎo", components: ["小", "丿"], clue: "A basic adjective meaning “few / little”." },
  "冷": { pinyin: "lěng", radical: "冫", components: ["令"], clue: "The ice radical 冫 fits 冷 “cold”." },
  "热": { pinyin: "rè", radical: "灬", components: ["执"], clue: "The fire dots 灬 fit 热 “hot”." },
  "高": { pinyin: "gāo", components: [], clue: "A basic adjective meaning “high / tall”." },
  "兴": { pinyin: "xìng", components: ["八", "一", "小"], clue: "In 高兴, 兴 helps form the idea “happy / glad”." },
  "漂": { pinyin: "piào", radical: "氵", components: ["票"], clue: "The water radical 氵 appears in 漂亮, the common word for “pretty”." },
  "亮": { pinyin: "liàng", components: ["亠", "口", "冖", "几"], clue: "亮 means bright; in 漂亮 it helps form the meaning “beautiful / pretty”." }
};
